package:
  version: "{{ PROJECT_VERSION }}"
  name: 'pycydemo'

source:
  path: ../../

build:
  script_env:
   - PROJECT_VERSION
  number: 0
  script: python setup.py install

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - numpy
    - cython >=0.24.1
    - setuptools
    - nose
  run:
    - numpy
test:
  requires:
    - python
    - nose
  commands:
    - conda inspect linkages pycydemo
    - nosetests -v --detailed-errors pycydemo 

about:
  description: Demo python+cython project
  home: https://github.com/theochem/python-cython-ci-example
  license: MIT

extra:
  recipe-maintainers: Toon Verstraelen <toon.verstraelen@gmail.com>
